from __future__ import annotations

import argparse
import asyncio
import csv
import json
import shutil
import subprocess
import sys
import wave
from dataclasses import dataclass
from pathlib import Path

import imageio_ffmpeg

import tts


DEFAULT_VOICE = "ru-RU-DmitryNeural"
RU_VOICES = ("ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural")


@dataclass
class Line:
    id: str
    speaker: str
    voice: str
    rate: str
    pitch: str
    volume: str
    radio: bool
    text: str


def safe_id(value: str) -> str:
    allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
    cleaned = "".join(ch if ch in allowed else "_" for ch in value.strip())
    cleaned = "_".join(part for part in cleaned.split("_") if part)
    if not cleaned:
        raise ValueError("empty id in CSV")
    return cleaned.lower()


def yes(value: str) -> bool:
    return value.strip().lower() in {"1", "yes", "true", "y", "да", "д"}


def read_lines(path: Path, default_voice: str) -> list[Line]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        rows: list[Line] = []
        for index, row in enumerate(reader, start=2):
            text = (row.get("text") or "").strip()
            if not text:
                continue
            line_id = safe_id(row.get("id") or f"line_{index:03d}")
            rows.append(
                Line(
                    id=line_id,
                    speaker=(row.get("speaker") or "").strip(),
                    voice=(row.get("voice") or default_voice).strip() or default_voice,
                    rate=(row.get("rate") or "+0%").strip() or "+0%",
                    pitch=(row.get("pitch") or "+0Hz").strip() or "+0Hz",
                    volume=(row.get("volume") or "+0%").strip() or "+0%",
                    radio=yes(row.get("radio") or "yes"),
                    text=text,
                )
            )
    return rows


def ffmpeg() -> str:
    return imageio_ffmpeg.get_ffmpeg_exe()


def run_ffmpeg(args: list[str]) -> None:
    cmd = [ffmpeg(), "-hide_banner", "-loglevel", "error", "-y", *args]
    subprocess.run(cmd, check=True)


def filters(radio: bool) -> str:
    chain = ["loudnorm=I=-18:TP=-1.5:LRA=11"]
    if radio:
        chain.extend(
            [
                "highpass=f=280",
                "lowpass=f=3200",
                "acompressor=threshold=-20dB:ratio=3:attack=8:release=120",
                "volume=1.45",
                "alimiter=limit=0.94",
            ]
        )
    return ",".join(chain)


def convert_audio(src: Path, dst: Path, fmt: str, sample_rate: int, radio: bool) -> None:
    common = ["-i", str(src), "-vn", "-ac", "1", "-ar", str(sample_rate), "-af", filters(radio)]
    if fmt == "wav":
        run_ffmpeg([*common, "-c:a", "pcm_s16le", str(dst)])
    elif fmt == "ogg":
        run_ffmpeg([*common, "-c:a", "libvorbis", "-q:a", "4", str(dst)])
    else:
        raise ValueError(f"unsupported format: {fmt}")


def wav_duration(path: Path) -> float | None:
    if not path.exists() or path.suffix.lower() != ".wav":
        return None
    with wave.open(str(path), "rb") as f:
        return f.getnframes() / float(f.getframerate())


def dcs_lua_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_manifests(rows: list[dict], out_dir: Path) -> None:
    manifest_json = out_dir / "manifest.json"
    manifest_csv = out_dir / "manifest.csv"
    snippets = out_dir / "dcs_sound_snippets.lua"

    manifest_json.write_text(
        json.dumps(rows, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    with manifest_csv.open("w", encoding="utf-8-sig", newline="") as f:
        fieldnames = ["id", "speaker", "voice", "wav", "ogg", "duration_sec", "text"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})

    lines = [
        "-- Generated by DCS RadioForge.",
        "-- If these files are packed into l10n/DEFAULT inside the .miz,",
        "-- use trigger.action.outSound with the l10n/DEFAULT path.",
        "",
        "DCS_RU_VOICEKIT = {",
    ]
    for row in rows:
        audio = row.get("ogg") or row.get("wav")
        lines.append(f'  ["{row["id"]}"] = {{')
        lines.append(f'    speaker = "{dcs_lua_string(row["speaker"])}",')
        lines.append(f'    file = "l10n/DEFAULT/{dcs_lua_string(audio)}",')
        lines.append(f'    text = "{dcs_lua_string(row["text"])}",')
        lines.append("  },")
    lines.extend(
        [
            "}",
            "",
            "function dcs_ru_voice(id, seconds)",
            "  local item = DCS_RU_VOICEKIT[id]",
            "  if not item then return end",
            "  trigger.action.outSound(item.file)",
            "  if item.text and item.text ~= \"\" then",
            "    local prefix = item.speaker ~= \"\" and (item.speaker .. \": \") or \"\"",
            "    trigger.action.outText(prefix .. item.text, seconds or 10)",
            "  end",
            "end",
            "",
            "-- Example:",
            '-- dcs_ru_voice("darkstar_start", 12)',
        ]
    )
    snippets.write_text("\n".join(lines) + "\n", encoding="utf-8")


async def generate(args: argparse.Namespace) -> int:
    input_path = Path(args.input).resolve()
    out_dir = Path(args.out).resolve()
    temp_dir = out_dir / "_tmp_mp3"
    ready_dir = out_dir / "dcs-ready"
    temp_dir.mkdir(parents=True, exist_ok=True)
    ready_dir.mkdir(parents=True, exist_ok=True)

    output_formats = ["wav", "ogg"] if args.format == "both" else [args.format]
    lines = read_lines(input_path, args.voice)
    if not lines:
        print("No lines found in CSV.", file=sys.stderr)
        return 1

    rows: list[dict] = []
    for line in lines:
        print(f"[tts] {line.id}: {line.speaker or line.voice}")
        mp3_path = temp_dir / f"{line.id}.mp3"
        await tts.synthesize_mp3(line.text, line.voice, line.rate, line.pitch, line.volume, mp3_path)

        wav_name = ""
        ogg_name = ""
        for fmt in output_formats:
            target = ready_dir / f"{line.id}.{fmt}"
            convert_audio(mp3_path, target, fmt, args.sample_rate, line.radio)
            if fmt == "wav":
                wav_name = target.name
            if fmt == "ogg":
                ogg_name = target.name

        duration = wav_duration(ready_dir / wav_name) if wav_name else None
        rows.append(
            {
                "id": line.id,
                "speaker": line.speaker,
                "voice": line.voice,
                "wav": wav_name,
                "ogg": ogg_name,
                "duration_sec": round(duration, 2) if duration is not None else "",
                "text": line.text,
            }
        )

    write_manifests(rows, out_dir)
    print(f"Done: {ready_dir}")
    return 0


def list_voices() -> int:
    for voice in RU_VOICES:
        print(voice)
    return 0


def clean(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    print(f"Removed: {out_dir}")
    return 0


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate Russian DCS voiceover files.")
    sub = p.add_subparsers(dest="command", required=True)

    g = sub.add_parser("generate", help="generate WAV/OGG files from CSV")
    g.add_argument("--input", default="lines.csv")
    g.add_argument("--out", default="build")
    g.add_argument("--voice", default=DEFAULT_VOICE)
    g.add_argument("--format", choices=["wav", "ogg", "both"], default="both")
    g.add_argument("--sample-rate", type=int, default=22050)

    sub.add_parser("voices", help="show recommended Russian voices")

    c = sub.add_parser("clean", help="remove build directory")
    c.add_argument("--out", default="build")
    return p


def main() -> int:
    args = parser().parse_args()
    if args.command == "generate":
        return asyncio.run(generate(args))
    if args.command == "voices":
        return list_voices()
    if args.command == "clean":
        return clean(args)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
